name: spellcheck
on:
  pull_request:
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.29.0
      name: Spellcheck
      with:
        source_files: README.md .github/CODE_OF_CONDUCT.md
        task_name: Markdown
        output_file: spellcheck-output.txt
